# Generated by Django 6.0 on 2026-03-29 00:10

import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('city', models.CharField(max_length=150, verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Brasserie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BeerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom')),
                ('image', models.ImageField(blank=True, null=True, upload_to='beers/', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('bitterness', models.IntegerField(default=0, verbose_name='Amertume (IBU)')),
                ('degree', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Degré')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Slug')),
                ('brewery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brewery')),
            ],
            options={
                'verbose_name': 'Bière',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('note', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Note /10')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beer')),
                ('drinker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dégustation',
                'ordering': ['-date'],
            },
        ),
    ]
