# Generated by Django 6.0 on 2025-12-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beeruser',
            old_name='mail',
            new_name='email',
        ),
        migrations.AddField(
            model_name='beeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
