# Generated by Django 6.0 on 2026-03-29 15:59

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_beer_added_by_beer_style_beeruser_bio_userfollow'),
    ]

    operations = [
        VectorExtension(),
        
        migrations.AddField(
            model_name='beer',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
