# Generated by Django 6.0 on 2025-12-27 14:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_mail_beeruser_email_beeruser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('bitterness', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('degree', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('brewery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brewery')),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('note', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=500)),
                ('beer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.beer')),
                ('drinker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
