# Generated by Django 6.0 on 2025-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_brewery_beer_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='comment',
            field=models.TextField(),
        ),
    ]
