# Generated by Django 6.0 on 2026-04-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_beer_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='drinks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
