# Generated by Django 6.0 on 2025-12-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_beer_descritpion_alter_brewery_descritpion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='bitterness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beer',
            name='degree',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
