# Generated by Django 6.0 on 2026-05-09 09:43

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_drinks_created_at_drinks_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
