# Generated by Django 6.0 on 2025-12-28 17:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_beer_bitterness_alter_beer_degree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['name'], 'verbose_name': 'Bière'},
        ),
        migrations.AlterModelOptions(
            name='beeruser',
            options={'verbose_name': 'Utilisateur'},
        ),
        migrations.AlterModelOptions(
            name='brewery',
            options={'ordering': ['name'], 'verbose_name': 'Brasserie'},
        ),
        migrations.AlterModelOptions(
            name='drinks',
            options={'ordering': ['-date'], 'verbose_name': 'Dégustation'},
        ),
        migrations.AlterField(
            model_name='beer',
            name='bitterness',
            field=models.IntegerField(default=0, verbose_name='Amertume (IBU)'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='degree',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Degré'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='city',
            field=models.CharField(max_length=150, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='comment',
            field=models.TextField(verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='note',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Note /10'),
        ),
    ]
