# Generated by Django 6.0 on 2026-05-09 09:48

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_beer_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
