# Generated by Django 6.0 on 2026-05-09 10:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_beer_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du lieu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Souvenirs')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drinks', models.ManyToManyField(blank=True, related_name='spots', to='app.drinks', verbose_name='Dégustations associées')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lieu de dégustation',
                'ordering': ['-date'],
            },
        ),
    ]
