# Generated by Django 6.0 on 2026-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_beer_options_alter_beeruser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='slug',
            field=models.SlugField(blank=True, default=models.CharField(max_length=150, unique=True, verbose_name='Nom'), max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
