# Generated by Django 6.0 on 2026-05-09 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_beerspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerspot',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='shared_spots', to=settings.AUTH_USER_MODEL, verbose_name='Amis associés'),
        ),
    ]
