# Generated by Django 6.0 on 2026-03-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_beer_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='beers/', verbose_name='Image'),
        ),
    ]
