# Generated by Django 6.0 on 2026-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_beerspot_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Supprimée du catalogue'),
        ),
    ]
