# Generated by Django 6.0 on 2026-05-10 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_beer_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam ou publicité'), ('offensive', 'Contenu offensant / haineux'), ('fake', 'Fausse information / Faux profil'), ('other', 'Autre raison')], max_length=20, verbose_name='Raison')),
                ('description', models.TextField(max_length=1000, verbose_name='Description détaillée')),
                ('status', models.CharField(choices=[('pending', 'Envoyé'), ('review', "En cours d'examen"), ('resolved', 'Traité')], default='pending', max_length=20, verbose_name='Statut')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name="Décision de l'administrateur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('reported_beer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.beer', verbose_name='Bière signalée')),
                ('reported_drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.drinks', verbose_name='Dégustation signalée')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Membre signalé')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Signalement',
                'ordering': ['-created_at'],
            },
        ),
    ]
