# Generated by Django 6.0 on 2026-06-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='breweries/', verbose_name='Image'),
        ),
    ]
