# Generated by Django 6.0 on 2026-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_brewery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='bitterness',
            field=models.IntegerField(blank=True, null=True, verbose_name='Amertume (IBU)'),
        ),
    ]
