# Generated by Django 6.0 on 2026-07-14 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_beer_bitterness'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='top_beer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.beer'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='top_beer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.beer'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='top_beer_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.beer'),
        ),
    ]
