# Generated by Django 6.0 on 2026-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_drinkreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('beer_shared', 'Bière goûtée en commun'), ('beer_added', "Nouvelle bière d'un abonnement"), ('achievement', 'Nouveau trophée'), ('spot_invite', 'Invitation à un lieu'), ('spot_updated', 'Lieu mis à jour'), ('beer_updated', 'Bière mise à jour'), ('drink_liked', 'Avis aimé'), ('report_updated', 'Signalement mis à jour')], max_length=20),
        ),
    ]
