# Generated by Django 6.0 on 2026-07-22 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_notification_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre du carnet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drinks', models.ManyToManyField(blank=True, related_name='notebooks', to='app.drinks', verbose_name='Dégustations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_notebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carnet personnalisé',
                'ordering': ['-created_at'],
            },
        ),
    ]
