# Generated by Django 6.0 on 2026-07-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_customnotebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='wishlist_beers',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='app.beer', verbose_name='Wishlist'),
        ),
    ]
