# Generated by Django 6.0 on 2026-07-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_notification_notif_type_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='notif_achievements',
            field=models.BooleanField(default=True, verbose_name='Trophées et récompenses'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='notif_follow',
            field=models.BooleanField(default=True, verbose_name='Nouveaux abonnés'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='notif_global',
            field=models.BooleanField(default=True, verbose_name='Toutes les notifications'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='notif_network',
            field=models.BooleanField(default=True, verbose_name='Réseau (Ajouts de bières, Lieux)'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='notif_social',
            field=models.BooleanField(default=True, verbose_name='Interactions (Likes, Wishlists)'),
        ),
    ]
