# Generated by Django 6.0 on 2026-08-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_beeruser_notif_achievements_beeruser_notif_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description officielle'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('beer_shared', 'Bière goûtée en commun'), ('beer_added', "Nouvelle bière d'un abonnement"), ('achievement', 'Nouveau trophée'), ('spot_invite', 'Invitation à un lieu'), ('spot_updated', 'Lieu mis à jour'), ('beer_updated', 'Bière mise à jour'), ('drink_liked', 'Avis aimé'), ('report_updated', 'Signalement mis à jour'), ('wishlist_added', 'Bière ajoutée à la liste de souhaits'), ('feedback_replied', 'Réponse à votre feedback')], max_length=20),
        ),
    ]
