# Generated by Django 6.0 on 2026-08-12 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_beer_description_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='bitterness',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)], verbose_name='IBU'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='degree',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Degré'),
        ),
    ]
