# Generated by Django 6.0 on 2026-08-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_brewery_city_brewery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bar',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='bar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bars/', verbose_name='Image'),
        ),
    ]
