# Generated by Django 6.0 on 2026-08-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_bar_city_remove_bar_is_deleted_bar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Amateur de bière'), ('bar', 'Gérant de Bar'), ('brewery', 'Brasserie')], default='regular', max_length=20, verbose_name='Type de profil'),
        ),
    ]
