# Generated by Django 6.0 on 2026-08-14 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_beeruser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_bars', to=settings.AUTH_USER_MODEL, verbose_name='Gérants'),
        ),
        migrations.AddField(
            model_name='bar',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Numéro SIRET'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_breweries', to=settings.AUTH_USER_MODEL, verbose_name='Gérants'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='siret',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Numéro SIRET'),
        ),
    ]
