# Generated by Django 6.0 on 2026-08-14 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_bar_managers_bar_siret_brewery_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beeruser',
            name='user_type',
        ),
    ]
