# Generated by Django 6.0 on 2026-08-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_beeruser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
