# Generated by Django 6.0 on 2026-08-14 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_bar_name_alter_brewery_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.brewery'),
        ),
    ]
