# Generated by Django 6.0 on 2026-08-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_notification_brewery'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bar'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brewery'),
        ),
    ]
