# Generated by Django 6.0 on 2026-08-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_notification_bar_alter_notification_brewery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('beer_shared', 'Bière goûtée en commun'), ('beer_added', "Nouvelle bière d'un abonnement"), ('achievement', 'Nouveau trophée'), ('spot_invite', 'Invitation à un lieu'), ('spot_updated', 'Lieu mis à jour'), ('beer_updated', 'Bière mise à jour'), ('drink_liked', 'Avis aimé'), ('report_updated', 'Signalement mis à jour'), ('wishlist_added', 'Bière ajoutée à la liste de souhaits'), ('feedback_replied', 'Réponse à votre feedback')], max_length=50),
        ),
    ]
