# Generated by Django 6.0 on 2026-08-20 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='note',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Note'),
        ),
    ]
