# Generated by Django 6.0 on 2026-08-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_drinks_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beeruser',
            name='is_staff',
        ),
    ]
