# Generated by Django 6.0 on 2026-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_beeruser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='show_establishments',
            field=models.BooleanField(default=True, verbose_name='Afficher mes établissements publiquement'),
        ),
    ]
