# Generated by Django 6.0 on 2026-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_beeruser_show_establishments'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Firebase Android'),
        ),
    ]
