# Generated by Django 6.0 on 2026-09-30 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_beeruser_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisation du chat IA',
                'unique_together': {('user', 'day')},
            },
        ),
    ]
