# Generated by Django 6.0 on 2026-09-30 12:05

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_chatusage'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='beeruser',
            managers=[
                ('objects', app.models.BeerUserManager()),
            ],
        ),
    ]
