# Generated by Django 6.0 on 2026-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_beeruser_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Décocher pour suspendre le compte : connexion refusée et profil masqué.', verbose_name='Compte actif'),
        ),
    ]
