# Generated by Django 6.0 on 2026-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_beeruser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_beer_name', violation_error_message='Une bière du catalogue porte déjà ce nom.'),
        ),
    ]
