# Generated by Django 6.0 on 2026-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_beer_unique_active_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beeruser',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token Firebase Android'),
        ),
    ]
