# Generated by Django 6.0 on 2026-09-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_beeruser_fcm_token_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brewery', verbose_name='Brasserie signalée'),
        ),
    ]
