# Generated by Django 6.0 on 2026-10-02 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_username_guardrails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('beer_shared', 'Bière goûtée en commun'), ('beer_added', "Nouvelle bière d'un abonnement"), ('achievement', 'Nouveau trophée'), ('spot_invite', 'Invitation à un lieu'), ('spot_updated', 'Lieu mis à jour'), ('beer_updated', 'Bière mise à jour'), ('drink_liked', 'Avis aimé'), ('report_updated', 'Signalement mis à jour'), ('wishlist_added', 'Bière ajoutée à la liste de souhaits'), ('feedback_replied', 'Réponse à votre feedback'), ('content_removed', 'Contenu retiré par la modération')], max_length=50),
        ),
        migrations.CreateModel(
            name='ModerationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('beer', 'Bière'), ('comment', 'Commentaire'), ('brewery', 'Brasserie'), ('bar', 'Bar'), ('user', 'Membre')], max_length=20)),
                ('action', models.CharField(choices=[('created', 'Création'), ('modified', 'Modification')], max_length=10)),
                ('object_id', models.PositiveBigIntegerField(verbose_name="Identifiant de l'objet")),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('context', models.CharField(blank=True, max_length=255, verbose_name='Contexte')),
                ('changes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Contenu à valider',
                'verbose_name_plural': 'Contenus à valider',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reviewed_at', 'kind', 'action'], name='moderation_queue_idx'), models.Index(fields=['kind', 'object_id'], name='moderation_object_idx')],
            },
        ),
    ]
