# Generated by Django 6.0 on 2026-10-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_moderation_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='notif_establishment',
            field=models.BooleanField(default=True, verbose_name='Établissements (Équipe, mises à jour)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('beer_shared', 'Bière goûtée en commun'), ('beer_added', "Nouvelle bière d'un abonnement"), ('achievement', 'Nouveau trophée'), ('spot_invite', 'Invitation à un lieu'), ('spot_updated', 'Lieu mis à jour'), ('beer_updated', 'Bière mise à jour'), ('drink_liked', 'Avis aimé'), ('wishlist_added', 'Bière ajoutée à la liste de souhaits'), ('manager_added', "Nommé dans l'équipe d'un établissement"), ('manager_removed', "Retiré de l'équipe d'un établissement"), ('place_updated', 'Établissement mis à jour'), ('beer_added_to_brewery', 'Bière ajoutée à votre brasserie'), ('beer_updated_by_manager', 'Bière modifiée par la brasserie'), ('beer_deleted_by_manager', 'Bière retirée par la brasserie'), ('report_updated', 'Signalement mis à jour'), ('feedback_replied', 'Réponse à votre feedback'), ('content_removed', 'Contenu retiré par la modération')], max_length=50),
        ),
    ]
