# Generated by Django 6.0 on 2026-10-03 09:44

import app.services.profile_pictures
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_verifiable_beers'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=app.services.profile_pictures.profile_pictures_storage, upload_to=app.services.profile_pictures.profile_picture_path, verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
