# Generated by Django 6.0 on 2026-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_block_report_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_e4', models.IntegerField(help_text='Latitude × 10 000, arrondie')),
                ('lon_e4', models.IntegerField(help_text='Longitude × 10 000, arrondie')),
                ('place_kind', models.CharField(blank=True, choices=[('home', 'Domicile / habitation'), ('bar', 'Bar, pub, restaurant'), ('brewery', 'Brasserie'), ('outdoor', 'Extérieur (parc, nature)'), ('street', 'Voie publique'), ('other', 'Autre')], max_length=10)),
                ('settlement', models.CharField(blank=True, help_text='city, town, village ou hamlet', max_length=10)),
                ('is_urban', models.BooleanField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('osm_category', models.CharField(blank=True, max_length=50)),
                ('osm_type', models.CharField(blank=True, max_length=50)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Géocodage inverse',
                'constraints': [models.UniqueConstraint(fields=('lat_e4', 'lon_e4'), name='unique_reverse_geocode_position')],
            },
        ),
    ]
