# Generated by Django 6.0 on 2026-10-03 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_reverse_geocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(max_length=30)),
                ('order', models.JSONField(default=list)),
                ('hidden', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Disposition d'analytics",
                'constraints': [models.UniqueConstraint(fields=('user', 'page_key'), name='unique_analytics_layout_per_page')],
            },
        ),
    ]
