# Generated by Django 6.0 on 2026-10-03 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_analytics_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Vue d'analytics",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('spec', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='app.analyticsview')),
            ],
            options={
                'verbose_name': "Tuile d'analytics",
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='analyticsview',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_analytics_view_name_per_user'),
        ),
    ]
