# Generated by Django 6.0 on 2026-10-03 20:31

import app.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_analytics_custom_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='slug',
            field=app.fields.PublicSlugField(blank=True, editable=False, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='toasted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_kind', models.CharField(choices=[('member', 'Membre'), ('team', 'Équipe')], max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_messages', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.feedback')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
