# Generated by Django 6.0 on 2026-10-04 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_plain_text_report_responses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='Identifiant du compte')),
                ('reason', models.CharField(choices=[('inactivity', 'Inactivité'), ('self', 'Demande du membre')], max_length=20)),
                ('last_activity_at', models.DateTimeField(verbose_name='Dernière activité')),
                ('was_warned', models.BooleanField(default=False, verbose_name='Prévenu avant suppression')),
                ('deleted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Compte supprimé',
                'verbose_name_plural': 'Comptes supprimés',
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AddField(
            model_name='beeruser',
            name='inactivity_warned_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Prévenu de la suppression le'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Dernière activité'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('beer_shared', 'Bière goûtée en commun'), ('beer_added', "Nouvelle bière d'un abonnement"), ('achievement', 'Nouveau trophée'), ('spot_invite', 'Invitation à un lieu'), ('spot_updated', 'Lieu mis à jour'), ('beer_updated', 'Bière mise à jour'), ('drink_liked', 'Avis aimé'), ('wishlist_added', 'Bière ajoutée à la liste de souhaits'), ('manager_added', "Nommé dans l'équipe d'un établissement"), ('manager_removed', "Retiré de l'équipe d'un établissement"), ('place_updated', 'Établissement mis à jour'), ('beer_added_to_brewery', 'Bière ajoutée à votre brasserie'), ('beer_updated_by_manager', 'Bière modifiée par la brasserie'), ('beer_deleted_by_manager', 'Bière retirée par la brasserie'), ('report_updated', 'Signalement mis à jour'), ('feedback_replied', 'Réponse à votre feedback'), ('content_removed', 'Contenu retiré par la modération'), ('inactivity_warning', 'Compte bientôt supprimé pour inactivité'), ('block_follow_up', 'Un problème avec un membre bloqué ?')], max_length=50),
        ),
    ]
