# Generated by Django 6.0 on 2026-10-04 08:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_inactive_accounts_rgpd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatusage',
            options={'verbose_name': "Utilisation de l'IA"},
        ),
        migrations.AlterUniqueTogether(
            name='chatusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatusage',
            name='scope',
            field=models.CharField(default='chat', max_length=20),
        ),
        migrations.AlterField(
            model_name='bar',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='markup_not_allowed', flags=0, message='Les caractères < et > ne sont pas autorisés.', regex='\\A[^<>]*\\Z')], verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='markup_not_allowed', flags=0, message='Les caractères < et > ne sont pas autorisés.', regex='\\A[^<>]*\\Z')], verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='markup_not_allowed', flags=0, message='Les caractères < et > ne sont pas autorisés.', regex='\\A[^<>]*\\Z')], verbose_name='Nom'),
        ),
        migrations.AlterUniqueTogether(
            name='chatusage',
            unique_together={('user', 'day', 'scope')},
        ),
        migrations.CreateModel(
            name='ThrottleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=40)),
                ('key_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'key_hash', 'created_at'], name='throttle_lookup_idx')],
            },
        ),
    ]
