# Generated by Django 6.0 on 2026-10-04 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_security_hardening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('follow', 'Nouvel abonné'), ('beer_shared', 'Bière goûtée en commun'), ('beer_added', "Nouvelle bière d'un abonnement"), ('achievement', 'Nouveau trophée'), ('spot_invite', 'Invitation à un lieu'), ('spot_updated', 'Lieu mis à jour'), ('beer_updated', 'Bière mise à jour'), ('drink_liked', 'Avis aimé'), ('wishlist_added', 'Bière ajoutée à la liste de souhaits'), ('manager_added', "Nommé dans l'équipe d'un établissement"), ('manager_removed', "Retiré de l'équipe d'un établissement"), ('place_updated', 'Établissement mis à jour'), ('beer_added_to_brewery', 'Bière ajoutée à votre brasserie'), ('beer_updated_by_manager', 'Bière modifiée par la brasserie'), ('beer_deleted_by_manager', 'Bière retirée par la brasserie'), ('report_updated', 'Signalement mis à jour'), ('feedback_replied', 'Réponse à votre feedback'), ('content_removed', 'Contenu retiré par la modération'), ('inactivity_warning', 'Compte bientôt supprimé pour inactivité'), ('policy_updated', 'Politique de confidentialité mise à jour'), ('block_follow_up', 'Un problème avec un membre bloqué ?')], max_length=50),
        ),
        migrations.CreateModel(
            name='PolicyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='Ce qui a changé')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_count', models.PositiveIntegerField(default=0, verbose_name='Membres notifiés')),
                ('notify_by_email', models.BooleanField(default=False, verbose_name='Aussi par e-mail')),
                ('email_cursor', models.PositiveBigIntegerField(default=0, editable=False)),
                ('emails_sent', models.PositiveIntegerField(default=0, verbose_name='E-mails envoyés')),
                ('email_done', models.BooleanField(default=False, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Publiée par')),
            ],
            options={
                'verbose_name': 'Annonce de la politique de confidentialité',
                'verbose_name_plural': 'Annonces de la politique de confidentialité',
                'ordering': ['-created_at'],
            },
        ),
    ]
