# Generated by Django 6.0 on 2026-10-06 21:10

import app.services.official_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_drinks_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.services.official_images.bar_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description officielle'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.services.official_images.beer_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='beerspot',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description / Souvenirs'),
        ),
        migrations.AlterField(
            model_name='beeruser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='brewery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.services.official_images.brewery_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='customnotebook',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='comment',
            field=models.TextField(max_length=2000, verbose_name='Commentaire'),
        ),
    ]
