# Generated by Django 6.0 on 2026-10-06 21:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_image_paths_and_text_limits'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='beeruser',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email_ci', violation_error_message='Cet email est déjà utilisé par un autre membre.'),
        ),
    ]
