# Generated by Django 6.0 on 2026-10-07 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_unique_email_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='beeruser',
            name='marketing_consent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Choix enregistré le'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='marketing_consent_source',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, verbose_name='Origine du choix'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='marketing_opt_in',
            field=models.BooleanField(default=True, verbose_name='Reçoit les e-mails promotionnels'),
        ),
        migrations.AddField(
            model_name='beeruser',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='E-mail de bienvenue envoyé le'),
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='Objet')),
                ('body', models.TextField(max_length=5000, verbose_name='Message')),
                ('cta_label', models.CharField(blank=True, max_length=40, verbose_name='Texte du bouton')),
                ('cta_url', models.URLField(blank=True, max_length=300, verbose_name='Lien du bouton')),
                ('kind', models.CharField(choices=[('promotional', 'Promotionnel (hors membres désinscrits)'), ('service', 'Alerte obligatoire (tous les membres actifs)')], default='promotional', max_length=20, verbose_name='Type')),
                ('audience', models.CharField(choices=[('all', 'Tous les membres'), ('active', 'Membres actifs'), ('inactive', 'Membres inactifs'), ('custom', 'Liste personnalisée')], default='active', max_length=20, verbose_name='Audience')),
                ('activity_days', models.PositiveSmallIntegerField(default=90, verbose_name="Seuil d'inactivité (jours)")),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sending', 'Envoi en cours'), ('done', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('launched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Rédigée par')),
                ('custom_members', models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Membres choisis')),
                ('launched_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Lancée par')),
            ],
            options={
                'verbose_name': 'Campagne e-mail',
                'verbose_name_plural': 'Campagnes e-mail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sending', 'En cours'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='app.emailcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaign_recipient_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user'), name='unique_campaign_recipient')],
            },
        ),
    ]
