# Generated by Django 6.0 on 2026-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='ean',
            field=models.CharField(blank=True, editable=False, max_length=13, null=True, verbose_name='Code-barres EAN'),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.UniqueConstraint(condition=models.Q(('ean__isnull', False), ('is_deleted', False)), fields=('ean',), name='unique_active_beer_ean'),
        ),
    ]
