# Generated by Django 6.0 on 2026-10-08 16:23

import django.contrib.postgres.indexes
from django.db import migrations, models

from app.services import match_keys

BATCH = 500


def fill_match_keys(apps, schema_editor):
    """Calcule les clés de comparaison des bières et des brasseries déjà enregistrées (par lots)."""
    for model_name, kind in (('Brewery', match_keys.BREWERY), ('Beer', match_keys.BEER)):
        model = apps.get_model('app', model_name)
        batch = []
        for row in model.objects.only('pk', 'name').iterator(chunk_size=BATCH):
            row.name_key = match_keys.strict_key(row.name, kind)
            row.match_key = match_keys.loose_key(row.name, kind)
            batch.append(row)
            if len(batch) == BATCH:
                model.objects.bulk_update(batch, ['name_key', 'match_key'])
                batch = []
        if batch:
            model.objects.bulk_update(batch, ['name_key', 'match_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_beer_ean'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='beer',
            name='unique_active_beer_name',
        ),
        migrations.AddField(
            model_name='beer',
            name='match_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='beer',
            name='name_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='brewery',
            name='match_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='brewery',
            name='name_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.RunPython(fill_match_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='beer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['match_key'], name='beer_match_key_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='brewery',
            index=django.contrib.postgres.indexes.GinIndex(fields=['match_key'], name='brewery_match_key_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('brewery_id', 'name'), name='unique_active_beer_name_per_brewery', violation_error_message='Cette brasserie a déjà une bière de ce nom.'),
        ),
    ]
