# Generated by Django 6.0 on 2026-10-08 16:47

import django.utils.timezone
from django.db import migrations, models

from app.services import address as address_service

BATCH = 500


def _each(apps, convert):
    for model_name in ('Brewery', 'Bar'):
        model = apps.get_model('app', model_name)
        rows = []
        for row in model.objects.all().iterator(chunk_size=BATCH):
            convert(row)
            rows.append(row)
            if len(rows) == BATCH:
                model.objects.bulk_update(rows, _FIELDS[convert])
                rows = []
        if rows:
            model.objects.bulk_update(rows, _FIELDS[convert])


def _split(row):
    row.street, row.postal_code, row.city = address_service.parse(row.address)


def _join(row):
    row.address = address_service.compose(row.street, row.postal_code, row.city) or None


_FIELDS = {_split: ['street', 'postal_code', 'city'], _join: ['address']}


def split_addresses(apps, schema_editor):
    """Découpe les adresses existantes (« 5 Rue du Port, 29900 Concarneau ») en rue, code postal et ville."""
    _each(apps, _split)


def join_addresses(apps, schema_editor):
    _each(apps, _join)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_catalog_match_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='bar',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='bar',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse (numéro et rue)'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='postal_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='brewery',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresse (numéro et rue)'),
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=5)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code', 'city'), name='unique_postal_code_city')],
            },
        ),
        migrations.RunPython(split_addresses, join_addresses),
        migrations.RemoveField(
            model_name='bar',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brewery',
            name='address',
        ),
    ]
