# Generated by Django 6.0 on 2026-10-08 16:50

import django.contrib.postgres.indexes
from django.db import migrations, models

from app.services import match_keys


def fill_bar_keys(apps, schema_editor):
    """Calcule les clés de comparaison des bars déjà enregistrés."""
    bars = list(apps.get_model('app', 'Bar').objects.only('pk', 'name'))
    for bar in bars:
        bar.name_key = match_keys.strict_key(bar.name, match_keys.BAR)
        bar.match_key = match_keys.loose_key(bar.name, match_keys.BAR)
    apps.get_model('app', 'Bar').objects.bulk_update(bars, ['name_key', 'match_key'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_split_address_postal_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='match_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='bar',
            name='name_key',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=200),
        ),
        migrations.RunPython(fill_bar_keys, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='bar',
            index=django.contrib.postgres.indexes.GinIndex(fields=['match_key'], name='bar_match_key_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
