# Generated by Django 6.0 on 2026-10-08 16:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_bar_match_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishmentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(max_length=14, verbose_name='SIRET déclaré')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name="Message à l'équipe")),
                ('registry', models.JSONField(blank=True, default=dict, verbose_name='Contrôle du SIRET')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Acceptée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée par le demandeur')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='Motif du refus')),
                ('bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='app.bar')),
                ('brewery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='app.brewery')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Décidée par')),
            ],
            options={
                'verbose_name': "Revendication d'établissement",
                'verbose_name_plural': "Revendications d'établissement",
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bar__isnull', True), ('brewery__isnull', False)), models.Q(('bar__isnull', False), ('brewery__isnull', True)), _connector='OR'), name='claim_exactly_one_place'), models.UniqueConstraint(condition=models.Q(('brewery__isnull', False), ('status', 'pending')), fields=('claimant', 'brewery'), name='one_pending_claim_per_brewery'), models.UniqueConstraint(condition=models.Q(('bar__isnull', False), ('status', 'pending')), fields=('claimant', 'bar'), name='one_pending_claim_per_bar')],
            },
        ),
    ]
