"""
Django settings for pokebeer project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _
from django.urls import reverse_lazy
from pokebeer.database import get_databases

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

def _csv(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# Pas de joker `.vercel.app` : n'importe quel autre projet Vercel pourrait sinon être servi sous un hôte accepté.
# Vercel fournit lui-même l'URL de production et celle du déploiement ; un domaine personnalisé va dans ALLOWED_HOSTS.
ALLOWED_HOSTS = _csv('ALLOWED_HOSTS', 'localhost,127.0.0.1') + [
    host for host in (os.getenv('VERCEL_PROJECT_PRODUCTION_URL'), os.getenv('VERCEL_URL'), os.getenv('VERCEL_BRANCH_URL')) if host
]

# Sécurité CSRF pour Hugging Face (car HF est derrière un proxy HTTPS)
CSRF_TRUSTED_ORIGINS = [
    'https://flow-millot-pokebeer.hf.space',
    'https://*.hf.space'
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
# `Lax` : le navigateur n'envoie plus la session lors d'une requête venue d'un autre site. `None` n'est utile que si
# le site doit être affiché dans une iframe tierce (COOKIE_SAMESITE=None).
CSRF_COOKIE_SAMESITE = SESSION_COOKIE_SAMESITE = os.getenv('COOKIE_SAMESITE', 'Lax')

# HTTPS partout : redirection, HSTS (un an, sous-domaines compris) ; désactivés en développement (HTTP local).
SECURE_SSL_REDIRECT = not DEBUG
SECURE_HSTS_SECONDS = 0 if DEBUG else 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True

# Nombre de proxys de confiance devant l'application (Vercel : 1) ; sert à lire la vraie IP du visiteur.
TRUSTED_PROXY_COUNT = int(os.getenv('TRUSTED_PROXY_COUNT', 1))

# Chemin de l'administration (avec « / » final) : le changer évite les robots qui visent /admin/.
ADMIN_URL = os.getenv('ADMIN_URL', 'admin/')

SITE_ID = int(os.getenv('SITE_ID', 2))
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*']
ACCOUNT_USERNAME_MIN_LENGTH = 5
ACCOUNT_USERNAME_VALIDATORS = 'app.validators.USERNAME_VALIDATORS'
# Connexion Google déclenchée par un POST (jeton CSRF) : un lien piégé ne peut pas connecter un visiteur à un compte choisi
SOCIALACCOUNT_LOGIN_ON_GET = False

# Application definition

INSTALLED_APPS = [
    'storages',
    'tailwind',
    'theme',
    "unfold",
    "unfold.contrib.forms", 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django_cleanup.apps.CleanupConfig', # Doit TOUJOURS être placé en dernier pour intercepter toutes les suppressions
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.SecurityHeadersMiddleware',
    'app.middleware.ActivityMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'pokebeer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "app" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.supabase_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'pokebeer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DEBUG=True -> DEV_DATABASE_URL (jamais la prod), sinon DATABASE_URL. Voir pokebeer/database.py
DATABASES = get_databases(DEBUG)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
LANGUAGES = [
    ('fr', _('French')),
    ('en', _('English')),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'app/static'),
    os.path.join(BASE_DIR, 'theme/static'),
]

if DEBUG:
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

AUTH_USER_MODEL = "app.BeerUser"

# Django envoie « same-origin » par défaut : OpenStreetMap reçoit alors des tuiles sans Referer et répond 403
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

CSRF_COOKIE_HTTPONLY = False  # DOIT être False pour que le JS puisse lire le cookie via document.cookie
SESSION_COOKIE_AGE = 31536000
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# RGPD : un compte sans aucune visite depuis ce délai est supprimé, après un avertissement par notification.
INACTIVE_ACCOUNT_MONTHS = 24
INACTIVE_ACCOUNT_WARNING_DAYS = 30
# Secret de la tâche planifiée Vercel (envoyé en `Authorization: Bearer`) ; sans lui, l'endpoint est fermé.
CRON_SECRET = os.getenv('CRON_SECRET')

# --- E-mails transactionnels (réinitialisation du mot de passe) via le SMTP de Gmail ---
# EMAIL_HOST_PASSWORD est un « mot de passe d'application » Google (validation en 2 étapes requise), jamais le mot de passe du compte.
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 10
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'pokebeer.assistance@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# Sans mot de passe d'application (poste de développement), les e-mails s'affichent dans la console au lieu d'être envoyés
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST_PASSWORD else 'django.core.mail.backends.console.EmailBackend'
SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL', EMAIL_HOST_USER)
DEFAULT_FROM_EMAIL = f'Pokebeer <{EMAIL_HOST_USER}>'
# Les liens des e-mails partent de cette adresse fixe, jamais de l'en-tête Host de la requête (empoisonnement de lien)
PUBLIC_BASE_URL = os.getenv('PUBLIC_BASE_URL', 'http://localhost:8000' if DEBUG else 'https://pokebeer.vercel.app').rstrip('/')
# Validité d'un lien de réinitialisation (secondes) ; le lien ne sert qu'une fois (il dépend de l'ancien mot de passe)
PASSWORD_RESET_TIMEOUT = 3600
# Durée minimale d'une demande de réinitialisation : le temps de réponse ne révèle pas si l'adresse a un compte
PASSWORD_RESET_MIN_SECONDS = 3

# Le site ne peut être affiché en iframe que par lui-même (anti-clickjacking)
X_FRAME_OPTIONS = 'SAMEORIGIN'

#Nom du dossier contenant TailwindCSS
TAILWIND_APP_NAME = "theme"

if DEBUG:
    # Add django_browser_reload only in DEBUG mode
    INSTALLED_APPS += ["django_browser_reload"]

if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media').replace('\\', '/')

# Config pour websocket
SUPABASE_URL = os.getenv('SUPABASE_URL')
SUPABASE_ANON_KEY = os.getenv('SUPABASE_ANON_KEY')
SUPABASE_SERVICE_ROLE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')

# Configuration S3 Supabase pour les médias
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'eu-west-1')

# Nécessaire pour Supabase S3
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'
# Ne pas écraser les fichiers avec le même nom (ajoutera des caractères aléatoires)
AWS_S3_FILE_OVERWRITE = False

# Rendre les URLs générées publiques et propres (sans signature expirante)
AWS_QUERYSTRING_AUTH = False
supabase_domain = os.getenv('SUPABASE_URL', '').replace('https://', '')
AWS_S3_CUSTOM_DOMAIN = f"{supabase_domain}/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}"

# En DEBUG, les uploads restent en local (media/) pour ne pas polluer le bucket de prod
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage" if DEBUG else "storages.backends.s3.S3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Photos de profil : bucket Supabase dédié (public en lecture)
AWS_PROFILE_PICTURES_BUCKET = os.getenv('AWS_PROFILE_PICTURES_BUCKET')
if DEBUG:
    STORAGES["profile_pictures"] = {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {"location": os.path.join(MEDIA_ROOT, 'profile_pictures'), "base_url": f"{MEDIA_URL}profile_pictures/"},
    }
else:
    STORAGES["profile_pictures"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_PROFILE_PICTURES_BUCKET,
            "custom_domain": f"{supabase_domain}/storage/v1/object/public/{AWS_PROFILE_PICTURES_BUCKET}",
            "file_overwrite": False,
            "querystring_auth": False,
            # Le nom du fichier change à chaque envoi : le cache peut être définitif
            "object_parameters": {"CacheControl": "public, max-age=31536000, immutable"},
        },
    }

# Canal des notifications push Android : créé par l'application (NotificationChannels.kt) ; les deux doivent rester identiques
FCM_ANDROID_CHANNEL_ID = "pokebeer_channel"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")
CHAT_DAILY_LIMIT = 10
CHAT_MESSAGE_MAX_LENGTH = 5000
LABEL_DAILY_LIMIT = 20
LABEL_MAX_UPLOAD_BYTES = 4 * 1024 * 1024  # Vercel refuse de toute façon les requêtes de plus de 4,5 Mo
REPORT_DAILY_LIMIT = 10

UNFOLD = {
    "DASHBOARD_CALLBACK": "app.admin.dashboard_callback",
    "SITE_TITLE": "Pokebeer",
    "SITE_HEADER": "Pokebeer Administration",
    "SITE_SUBHEADER": "Outil de gestion et d'analyse",
    "SITE_DROPDOWN": [
        {
            "icon": "home",
            "title": _("Retour au site"),
            "link": "https://pokebeer.vercel.app/",
        },
        # ...
    ],
    "SITE_URL": "/",
    "SHOW_VIEW_ON_SITE": True, 
    "SHOW_UI_WARNINGS": True,
    "SIDEBAR": {
        "show_search": False, 
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Navigation"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard", 
                        "link": reverse_lazy("admin:index"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Membres"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:app_beeruser_changelist"),
                    },
                    {
                        "title": _("Rôles"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:app_beeruser_roles"),
                    },
                    {
                        "title": _("Comptes supprimés"),
                        "icon": "person_remove",
                        "link": reverse_lazy("admin:app_accountdeletion_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": _("Modération"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Contenus à valider"),
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:app_moderationentry_changelist"),
                        "badge": "app.admin.moderation.pending_count",
                        "permission": lambda request: request.user.is_staff,
                    },
                    {
                        "title": _("Feedback"),
                        "icon": "comment", 
                        "link": reverse_lazy("admin:app_feedback_changelist"),
                        "badge": "app.admin.pending.pending_feedback_count",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Personnes bloquées"),
                        "icon": "block",
                        "link": reverse_lazy("admin:app_userblock_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Signalement"),
                        "icon": "gavel", 
                        "link": reverse_lazy("admin:app_report_changelist"),
                        "badge": "app.admin.pending.pending_report_count",
                        "permission": lambda request: request.user.is_superuser,
                    },                              
                ],
            },
            {
                "title": _("Analytics"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": _(title), "icon": icon, "link": reverse_lazy("admin_analytics", args=[key]),
                     "permission": lambda request: request.user.is_staff}
                    for title, icon, key in (
                        ("Tendances", "trending_up", "trends"),
                        ("Goûts", "sports_bar", "tastes"),
                        ("Habitudes", "schedule", "habits"),
                        ("Géographie", "public", "geography"),
                        ("Établissements", "storefront", "places"),
                        ("Bars", "local_bar", "bars"),
                        ("Trophées", "emoji_events", "trophies"),
                    )
                ] + [
                    {"title": _("Custom"), "icon": "dashboard_customize", "link": reverse_lazy("admin_analytics_custom"),
                     "permission": lambda request: request.user.is_staff},
                ],
            },
            {
                "title": _("Contenu"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Bière"),
                        "icon": "beer_meal", 
                        "link": reverse_lazy("admin:app_beer_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Brasserie"),
                        "icon": "factory", 
                        "link": reverse_lazy("admin:app_brewery_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Bar"),
                        "icon": "chair_counter", 
                        "link": reverse_lazy("admin:app_bar_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },                                 
                ],
            },  
        ],
    },
}

# Notification Android
# Configuration Firebase
FIREBASE_CREDENTIALS_JSON = os.environ.get('FIREBASE_CREDENTIALS_JSON')